# Generated by Django 6.0.4 on 2026-05-21 06:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Halaqah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelompok', models.CharField(max_length=100)),
                ('tingkat', models.CharField(choices=[('TAKHASUS', 'Takhasus'), ('TAHSIN', 'Tahsin'), ('TAHFIDZ', 'Tahfidz')], max_length=20)),
                ('semester_aktif', models.CharField(default='2025-Ganjil', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin LPPIK'), ('KMF', 'Koordinator Mentoring Fakultas'), ('MENTOR', 'Mentor'), ('MENTEE', 'Mentee')], default='MENTEE', max_length=10)),
                ('nim', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='uploads/profile/')),
                ('no_hp', models.CharField(blank=True, default='', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InformasiKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('MENTORING', 'Info Mentoring'), ('CINTA_SUBUH', 'Cinta Subuh'), ('TABLIGH_AKBAR', 'Tabligh Akbar'), ('LAINNYA', 'Lainnya')], default='MENTORING', max_length=20)),
                ('deskripsi', models.TextField()),
                ('tanggal_kegiatan', models.DateField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='uploads/informasi/')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('pembuat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informasi_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='2025-Ganjil', max_length=50)),
                ('pertemuan_ke', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('topik', models.CharField(blank=True, default='', max_length=255)),
                ('deskripsi', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['semester', 'pertemuan_ke'],
                'unique_together': {('semester', 'pertemuan_ke')},
            },
        ),
        migrations.CreateModel(
            name='JurnalPertemuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pelaksanaan', models.DateField(auto_now_add=True)),
                ('mentor_hadir', models.BooleanField(default=True)),
                ('laporan_kegiatan', models.TextField(blank=True, null=True)),
                ('diisi_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurnal_diisi', to=settings.AUTH_USER_MODEL)),
                ('halaqah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurnal_pertemuan', to='toringmine.halaqah')),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurnal_pertemuan', to='toringmine.jadwal')),
            ],
            options={
                'unique_together': {('jadwal', 'halaqah')},
            },
        ),
        migrations.CreateModel(
            name='Koordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('fakultas', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='koordinator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MateriMentoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('tipe', models.CharField(choices=[('FILE', 'File / PDF'), ('LINK', 'Tautan'), ('VIDEO', 'Video')], default='FILE', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/materi/')),
                ('link_url', models.URLField(blank=True, max_length=500, null=True)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi_list', to='toringmine.jadwal')),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('prodi', models.CharField(max_length=100)),
                ('halaqah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anggota_mentee', to='toringmine.halaqah')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('no_hp', models.CharField(blank=True, default='', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='halaqah',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelompok_halaqah', to='toringmine.mentor'),
        ),
        migrations.CreateModel(
            name='Mutabaah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('materi_bacaan', models.CharField(help_text='Contoh: Al-Baqarah / Iqro Jilid 4', max_length=150)),
                ('rentang_bacaan', models.CharField(help_text='Contoh: Ayat 1-10 / Halaman 15', max_length=100)),
                ('nilai', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('catatan_mentor', models.TextField(blank=True, null=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutabaah_mentee', to='toringmine.mentee')),
            ],
        ),
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_sertifikat', models.CharField(max_length=100, unique=True)),
                ('sebagai', models.CharField(choices=[('MENTOR', 'Mentor'), ('MENTEE', 'Mentee')], max_length=20)),
                ('link_drive', models.URLField(max_length=500)),
                ('tanggal_terbit', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sertifikat_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('HADIR', 'Hadir'), ('IZIN', 'Izin'), ('SAKIT', 'Sakit'), ('ALPHA', 'Alpha')], default='ALPHA', max_length=10)),
                ('surat_izin', models.FileField(blank=True, null=True, upload_to='uploads/surat_izin/')),
                ('waktu_input', models.DateTimeField(auto_now=True)),
                ('jurnal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi_mentee_list', to='toringmine.jurnalpertemuan')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi_mentee', to='toringmine.mentee')),
            ],
            options={
                'unique_together': {('mentee', 'jurnal')},
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/resume/')),
                ('nilai', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('catatan_mentor', models.TextField(blank=True, null=True)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_jadwal', to='toringmine.jadwal')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_mentee', to='toringmine.mentee')),
            ],
            options={
                'unique_together': {('mentee', 'jadwal')},
            },
        ),
    ]
