# Generated by Django 6.0.4 on 2026-05-21 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toringmine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informasikegiatan',
            old_name='deskripsi',
            new_name='isi',
        ),
        migrations.RenameField(
            model_name='materimentoring',
            old_name='judul',
            new_name='topik',
        ),
        migrations.RenameField(
            model_name='materimentoring',
            old_name='link_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='topik',
        ),
        migrations.RemoveField(
            model_name='materimentoring',
            name='tipe',
        ),
        migrations.AddField(
            model_name='materimentoring',
            name='deskripsi',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='materimentoring',
            name='jadwal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi', to='toringmine.jadwal'),
        ),
    ]
