# Generated by Django 6.0.4 on 2026-04-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toringmine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='file_url',
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/resume/'),
        ),
    ]
