# Generated by Django 6.0.4 on 2026-04-27 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toringmine', '0002_remove_resume_file_url_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='kehadiran_mentor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='laporan_kegiatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_sertifikat', models.CharField(max_length=100, unique=True)),
                ('sebagai', models.CharField(choices=[('MENTOR', 'Mentor'), ('MENTEE', 'Mentee')], max_length=20)),
                ('link_drive', models.URLField(max_length=500)),
                ('tanggal_terbit', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sertifikat_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
