# Generated by Django 6.0.4 on 2026-05-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toringmine', '0002_rename_deskripsi_informasikegiatan_isi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LPPIK', 'Admin LPPIK'), ('KMF', 'Koordinator Mentoring Fakultas'), ('MENTOR', 'Mentor'), ('MENTEE', 'Mentee')], default='MENTEE', max_length=10),
        ),
    ]
