# Generated by Django 6.0.4 on 2026-05-22 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toringmine', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presensi',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='presensi',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presensi',
            name='jadwal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toringmine.jadwal'),
        ),
        migrations.AddField(
            model_name='presensi',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toringmine.mentor'),
        ),
        migrations.AlterField(
            model_name='presensi',
            name='jurnal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toringmine.jurnalpertemuan'),
        ),
        migrations.AlterField(
            model_name='presensi',
            name='mentee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toringmine.mentee'),
        ),
    ]
