# Generated by Django 6.0.4 on 2026-05-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toringmine', '0004_alter_presensi_unique_together_presensi_catatan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutabaah',
            name='pertemuan_ke',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
