# Generated by Django 6.0.4 on 2026-05-26 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toringmine', '0005_mutabaah_pertemuan_ke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutabaah',
            name='nilai',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='nilai',
        ),
    ]
