# Generated by Django 6.0.4 on 2026-05-26 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toringmine', '0006_remove_mutabaah_nilai_remove_resume_nilai'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='nilai',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
