# Generated by Django 6.0.4 on 2026-05-26 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toringmine', '0007_resume_nilai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sertifikat',
            name='link_drive',
        ),
        migrations.RemoveField(
            model_name='sertifikat',
            name='nomor_sertifikat',
        ),
        migrations.AddField(
            model_name='sertifikat',
            name='link_sertifikat',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sertifikat',
            name='sebagai',
            field=models.CharField(choices=[('MENTEE', 'Mentee'), ('MENTOR', 'Mentor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sertifikat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sertifikat_ku', to=settings.AUTH_USER_MODEL),
        ),
    ]
