# Generated by Django 6.0.4 on 2026-06-04 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toringmine', '0008_remove_sertifikat_link_drive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NilaiUjian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspek_1', models.IntegerField(default=0)),
                ('aspek_2', models.IntegerField(default=0)),
                ('aspek_3', models.IntegerField(default=0)),
                ('aspek_4', models.IntegerField(default=0)),
                ('aspek_5', models.IntegerField(default=0)),
                ('total_nilai', models.IntegerField(default=0, editable=False)),
                ('status_lulus', models.BooleanField(default=False, editable=False)),
                ('dinilai_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penilai', to=settings.AUTH_USER_MODEL)),
                ('mentee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_ujian', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
